const truthQuestions = [
  "Do you secretly fantasize about someone in this room?",
  "What turns you on about habits?",
  "Have you ever hidden a relationship from your friends?",
  "What’s the biggest lie you’ve ever told?",
  "What’s your biggest turn-on?",
  "Who’s the worst dressed in the room?",
  "What’s one thing you only do when you’re alone?",
  "Who’s your least favorite person in this room?",
  "What’s the weirdest thing you’ve ever eaten?",
  "What’s the strangest dream you’ve ever had?",
  "What’s the most embarrassing thing you’ve ever done?",
  "Have you ever peed yourself?",
  "What’s your craziest party story?",
  "Where’s your favorite place to fart in public?",
  "Have you ever walked in on your parents doing it?",
  "What would you do if you got locked in a store overnight?",
  "What’s the strangest thing you do while drunk?",
  "What’s the most disgusting thing you’ve ever done?",
  "Do you believe in aliens?",
   "What’s your biggest turn-off?",
  "What’s your biggest turn-on?",
  "What’s the largest age gap you’ve had with a partner?",
  "Which sexual act are you best at?",
  "Are you a part of the mile-high club?",
  "What’s your favorite body part?",
  "Have you ever gone skinny dipping?",
  "Where’s the weirdest place you’ve had sex?",
  "Have you ever faked it?",
  "What’s the most embarrassing thing that’s ever happened to you during sex?",
  "Do you have any fetishes?",
  "Do you do it with the lights on or off?",
  "What’s your craziest one-night stand story?",
  "What’s your guilty pleasure in the bedroom?",
  "What’s the last lie you told?",
  "What’s your biggest regret?",
  "Who do you text the most?",
  "What’s your biggest secret?",
  "Who’s the worst dressed in the room?",
  "Who was your worst kiss?",
  "Have you ever cheated on someone?",
  "Have you ever ghosted somebody?",
  "What’s the boldest pick-up line you’ve ever used?",
  "Who would you most like to date in this room?",
  "How would you rate your looks on a scale of 1 to 10?",
  "Have you ever broken the law?",
  "Who are you most jealous of?",
  "Who would you like to kiss in this room?",
  "What’s your guilty pleasure?",
  "If you could get back with an ex, who would you get back with?",
  "What’s your toxic trait?",
  "Is love or money more important?",
   "What’s a secret you’ve never told anyone?",
  "Do you have a favorite sibling?",
  "Do you have a favorite friend?",
  "What’s your biggest fear?",
  "Do you have a hidden talent?",
  "What’s the worst thing you’ve ever done?",
  "Who’s your least favorite person in this room?",
  "Who would you call to help you bury a body?",
  "What’s one thing you’d never do, even for 1 million dollars?",
  "When was the last time you lied?",
  "When was the last time you cried?",
  "What’s the worst thing you’ve ever said to somebody?",
  "What’s your biggest insecurity?",
  "What’s your most embarrassing childhood memory?",
  "What’s the weirdest place you’ve peed?",
  "Have you ever peed in the shower?",
  "What’s the strangest meal you’ve ever made?",
  "What’s your favorite gross food combination?",
  "What’s the oddest rumor you’ve heard about yourself?",
  "What’s one thing you only do when you’re alone?",
  "How many selfies do you take a day?",
  "What gives you the ick?",
  "What’s the longest you’ve ever gone without showering?",
  "Do you have a weird celebrity crush?",
  "What’s the most surprising thing in your bag?",
  "What do you love most about my body?",
  "What do you fear most in our relationship?",
  "What did you think about me when we first met?",
  "What’s the kinkiest thing you want us to try?",
  "How did you envision your future partner as a kid?",
  "Where do you think we’ll be in 10 years?",
  "What’s your ideal romantic evening like?",
  "What’s your favorite thing we do together?",
  "If we met earlier in life, do you think we’d be together?",
  "What do you love most about me?",
  "What are your 3 favorite positions?",
  "How would you define cheating?",
  "What do you think the key to a happy relationship is?",
  "Have I ever made you cry?",
  "What do you really think about my friends?",
  "What’s your biggest irrational fear?",
  "If you could fight any historical figure, who would it be?",
  "Do you pick your nose?",
  "Have you ever peed your pants as an adult?",
  "What’s your most useless skill?",
  "What’s the most unnecessary white lie you’ve ever told?",
  "What’s the worst date you’ve ever been on?",
  "Have you ever re-gifted something?",
  "Have you ever used my toothbrush?",
  "What’s the worst time you’ve laughed at something?",
  "What’s the funniest thing you believed in as a child?",
  "When’s the last time you were embarrassed?",
  "What’s the grossest thing you’ve ever done?",
  "What’s an embarrassing song you secretly love?"
  
];

const dareQuestions = [
  "Let someone in the group kiss you.",
  "Pretend you're a stripper for one minute.",
  "Pick someone and give them a flirty message.",
  "Breakdance for 45 seconds.",
  "Post on social media only using your feet.",
  "Close your eyes, sit on someone’s lap and guess who it is.",
  "Only say 'yes' for the next hour.",
  "Serenade the person on your left.",
  "Give a dramatic Shakespeare reading.",
  "Send your ex a message that you miss them.",
  "Ask a stranger for advice on a weird rash you’ve discovered on your butt.",
  "Seductively eat a banana while locking eyes with the person on your right.",
  "Do a seductive dance for the group.",
  "Close your eyes, pick a random phone contact and leave them a dirty message.",
  "Put an ice cube in your pants.",
  "Search the dirtiest thing you can think of online and show it to the person beside you.",
  "Tell one dirty secret no one knows about you.",
  "Do your best, sexy crawl.",
  "Eat a raw egg.",
  "Walk around the room like a chicken.",
  "Give a personalized insult to everyone in the room.",
  "Exchange an item of clothing with the person on your left.",
  "Call a parent and tell them you’ve eaten your vegetables.",
  "Juggle 3 things of the group’s choice.",
  "Pretend to be the person to your left for 5 minutes.",
  "Try to make the group laugh as quickly as possible.",
    "Let someone in this room post on your social media.",
  "Get an item from the kitchen and try to sell it to us in 2 minutes.",
  "Let the other players go through your phone for 1 minute.",
  "Drink a shot of pickle juice.",
  "Call your crush.",
  "Try to lick your elbow.",
  "Let another person draw on you with a permanent marker.",
  "Drink a mystery drink made by someone in the room.",
  "Let the group DM someone from your account.",
  "Keep 3 ice cubes in your mouth until they melt.",
  "Yell out the first word that comes to mind.",
  "Eat something of the group’s choice without using your hands.",
  "Let someone in the room touch up your makeup.",
  "Talk in a British accent for 10 minutes.",
  "Say 3 honest things to the group.",
  "Let someone shave a part of your body.",
  "Do 50 squats.",
  "Smell everyone’s armpits and rank them from worst to best.",
  "Eat a banana peel.",
  "Kiss a pillow like it’s your crush.",
  "Quack like a duck for 10 minutes.",
  "Crack an egg on your head.",
  "Shower with your clothes on.",
  "Write a love song about an object in the room.",
  "Show your favorite picture of yourself.",
  "Eat a raw piece of garlic.",
  "Twerk for 1 minute.",
  "Give a foot massage to the person on your left.",
  "Howl at the moon like a wolf.",
  "Play air guitar for 2 minutes.",
  "Let someone tickle you, and try not to laugh.",
  "Swap shoes with the person on your right.",
  "Take off one piece of clothing.",
  "Flirt badly with your partner for 1 minute.",
  "Give your partner a lap dance.",
  "Tell me a secret you’ve never told me before.",
  "Go skinny dipping.",
  "Let your partner choose your lock screen, and keep it for a week.",
  "Draw a romantic portrait of your partner.",
  "Write a romantic poem about your partner.",
  "Go to the window and scream, 'I’m in love!'",
  "Do a dramatic reading of dirty texts you’ve sent your partner.",
  "Act out you and your partner’s first kiss.",
  "Give your partner a foot massage."

  
];
